# -*- coding: utf-8 -*-
"""funnel-plotting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v_Xwq2UNgzQKEV39J5W_ITnAihMmmGK2

## Funnel Analysis
[video walkthrough](https://www.loom.com/share/973078f6535b411496824e8219c2c437)
"""

import streamlit as st
from google.colab import auth
auth.authenticate_user()

#@title Read Data
import gspread
import pandas as pd
from gspread_dataframe import get_as_dataframe

# Authenticate and create a client to access Google Sheets
from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google.auth import default

# Get Google Sheets API client
creds, _ = default()
gc = gspread.authorize(creds)

sheet_name = 'Funnel Analytics (2024 1/1-11/20)'
workbook = gc.open(sheet_name)

worksheet = workbook.worksheet("spend")
spend = get_as_dataframe(worksheet)

worksheet = workbook.worksheet("users")
users = get_as_dataframe(worksheet)

worksheet = workbook.worksheet("meta-ads-per-day")
ads = get_as_dataframe(worksheet)

for df in [spend, users, ads]:
  df.dropna(how='all', inplace=True)
  df.dropna(axis=1, how='all', inplace=True)

#@title User Funnel Data prep
users_cp = (
    users.assign(
        has_business=users['first_business'].notnull(),
        has_email=users['email'].notnull(),
        has_name=users['given_name'].notnull(),
        has_subscription=((users['subscription.subscription_id'].notna()) &
                          (users['subscription.is_appsumo'] == False)),
        created_at=pd.to_datetime(users['created_at'].apply(lambda x: x.split()[0]))
    )
    .set_index('created_at')
)
users_cp = users_cp[users_cp.index > '2024-01-01']

#@title Meta Ads Data Prep
ads_by_day = (
    ads
    .rename(columns={'Day': 'date'})
    .assign(date=lambda df: pd.to_datetime(df['date']))
    .set_index('date')
)

spend_cp = (
  spend
  .assign(date=lambda df: pd.to_datetime(spend.charge_date))
  .set_index('date')
  .resample('D').agg({
    'initial_spend': 'mean',
    'total_spend': 'mean',
  }))

merged_data = spend_cp.join(ads_by_day, how='inner')

#@title Get data to plot
import plotly.express as px

st.title("Funnel Analysis")

grouping_period = st.selectbox("Select Grouping Period", ["daily", "weekly", "monthly"])
grouping_map = {
    "daily": "D",
    "weekly": "W-Mon",
    "monthly": "M",
}

user_data_to_plot = (users_cp
  .resample(grouping_map[grouping_period]).agg({
      # 'index': 'count',
      'has_business': 'mean',
      'has_post': 'mean',
      'has_email': 'mean',
      'has_name': 'mean',
      'has_subscription': 'mean'
  })
  .assign(pct_subscribed_x10=lambda df: df['has_subscription'] * 10)
  .rename(columns={
      'created_at': 'created',
      'has_business': 'pct_has_business',
      'has_post': 'pct_has_post',
      'has_email': 'pct_has_email',
      'has_name': 'pct_has_name',
      'has_subscription': 'pct_has_subscription'
  })[['pct_has_business', 'pct_has_post', 'pct_has_email', 'pct_has_name', 'pct_subscribed_x10']]
)


usd_data_to_plot = (
   merged_data
     .resample(grouping_map[grouping_period])
     .apply(lambda x: pd.Series({
        'Initial Spend': x['initial_spend'].mean(),
        'Customer Total Spend': x['total_spend'].mean(),
        'CAC': (x['Cost per purchase'] * x['Purchases']).sum() / x['Purchases'].sum(),
        'CPC': (x['CPC (cost per link click)'] * x['Link clicks']).sum() / x['Link clicks'].sum(),
        'Ad Spend': x['Amount spent (USD)'].sum(),
     }))
)

count_data_to_plot = (
   merged_data
     .resample(grouping_map[grouping_period])
     .apply(lambda x: pd.Series({
         'Purchases': x['Purchases'].sum(),
         'Clicks': x['Link clicks'].mean(),
     }))
)

# Figure 1: Users Created
users_created_fig = px.line(
    (users_cp
      .resample(grouping_map[grouping_period])
      .size().rename('Users Created')),
    labels={"index": "Date", "value": "Count"},
    title="Users Created",
    height=400,
)
users_created_fig.update_xaxes(title_text="")
st.plotly_chart(users_created_fig)

# Figure 2: User Funnel
user_funnel_fig = px.line(
    user_data_to_plot,
    labels={"index": "Date", "value": "Percentage"},
    title="User Funnel",
    height=400,
)
user_funnel_fig.update_xaxes(title_text="")
st.plotly_chart(user_funnel_fig)

# Figure 3: CAC vs Spend
cac_spend_fig = px.line(
    usd_data_to_plot,
    labels={'value': 'USD', 'date': 'Date'},
    title="CAC vs Spend",
    height=400,
)
cac_spend_fig.update_xaxes(title_text="")
st.plotly_chart(cac_spend_fig)

# Figure 4: Count Data
count_fig = px.line(
    count_data_to_plot,
    labels={'value': 'Count', 'date': 'Date'},
    title="Ad Count Data",
    height=400,
)
count_fig.update_xaxes(title_text="")
st.plotly_chart(count_fig)
